# Generated by Django 3.1.6 on 2021-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('url', models.URLField(verbose_name='地址')),
                ('content', models.TextField(max_length=800, verbose_name='详细介绍')),
            ],
            options={
                'verbose_name': '收录内容',
                'verbose_name_plural': '收录内容',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='评分')),
                ('content', models.TextField(max_length=800, verbose_name='评分理由')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='推荐内容')),
                ('url', models.URLField(max_length=100, verbose_name='地址')),
                ('content', models.TextField(max_length=800, verbose_name='推荐理由')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
    ]
