# Generated by Django 3.1.6 on 2021-03-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='rate',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection', verbose_name='收录内容'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='collection',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.classification', verbose_name='类别'),
        ),
    ]
