# Generated by Django 3.2.16 on 2022-12-12 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='rate',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
