# Generated by Django 3.2.16 on 2022-12-12 13:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20221212_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='url',
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=100000, verbose_name='内容'),
        ),
    ]
