# Generated by Django 3.2.16 on 2022-12-13 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_collection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='hidden_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='隐藏内容'),
        ),
        migrations.AddField(
            model_name='collection',
            name='uuid',
            field=models.CharField(default=1, max_length=30, verbose_name='标识码'),
            preserve_default=False,
        ),
    ]
