# Generated by Django 3.2.16 on 2022-12-13 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20221213_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='hidden_content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='隐藏内容'),
        ),
    ]
