# Generated by Django 3.2.16 on 2022-12-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_collection_hidden_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='ip',
        ),
    ]
