# Generated by Django 3.2.16 on 2022-12-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='板块名称')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='classification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bbs.classification', verbose_name='板块'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bbs.type', verbose_name='类别'),
            preserve_default=False,
        ),
    ]
