# Generated by Django 3.2.16 on 2022-12-14 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20221214_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='submit_datetime',
        ),
        migrations.AddField(
            model_name='post',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bbs.type', verbose_name='类别'),
        ),
    ]
