# Generated by Django 3.2.16 on 2022-12-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20221214_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.post', verbose_name='回复对象'),
        ),
    ]
