# Generated by Django 3.2.16 on 2022-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20221215_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.classification', verbose_name='板块'),
        ),
    ]
