# Generated by Django 3.2.16 on 2022-12-13 08:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221212_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=30, verbose_name='版本')),
                ('title', models.CharField(max_length=300, verbose_name='协议标题')),
                ('content', ckeditor.fields.RichTextField(max_length=1000000, verbose_name='协议内容')),
                ('must_sign', models.BooleanField(default=True, verbose_name='必须签订')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户协议',
                'verbose_name_plural': '用户协议',
            },
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.CreateModel(
            name='AgreementSignRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agreement', verbose_name='协议')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户协议',
                'verbose_name_plural': '用户协议',
            },
        ),
    ]
