# Generated by Django 3.2.16 on 2022-12-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221213_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementsignrecord',
            options={'verbose_name': '用户协议签订记录', 'verbose_name_plural': '用户协议签订记录'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ip',
        ),
    ]
